# Copyright (c) 2026 Elias S. G. Carotti

[package]
name = "acoustic_ofdm_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
acoustic_ofdm = { path = "../lib" }
clap = { version = "4", features = ["derive"] }
cpal = "0.16"
log = "0.4"
rand = "0.9"
ringbuf = "0.4"
simplelog = "0.12"

# vim: set ts=4 sw=4 et:
